apiVersion: v1
kind: Namespace
metadata:
  name: user-api-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
  namespace: user-api-ns
  labels:
    k8s-app: user-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: user-api-app
  template:
    metadata:
      name: user-api-template
      labels:
        k8s-app: user-api-app
    spec:
      containers:
      - name: user-api-container
        image: localhost:32000/user-api:1.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-api-service
  namespace: user-api-ns
  labels:
    k8s-app: user-api-app
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    k8s-app: user-api-app
