create schema trailerplan authorization dba;

drop table P_USER if exists;

--===================================
-- create production table
--===================================
create table P_USER (
    ID int GENERATED by default as identity (start with 1 increment by 1) not null,
    FIRST_NAME VARCHAR(20) not null,
    LAST_NAME VARCHAR(20) not null,
    BIRTHDAY date null,
    MAIL VARCHAR (50) null,
    COUNTRY varchar(20) null,
    PRIMARY KEY (ID)
);
