create schema trailerplan authorization dba;

drop table P_USER if exists;

--===================================
-- create production table
--===================================
create table P_USER(
  ID int GENERATED by default as identity (start with 1 increment by 1) not null,
  VERSION int not null,
  CREATION_DATE date not null,
  UPDATE_DATE date null,
  FIRST_NAME VARCHAR(20) not null,
  LAST_NAME VARCHAR(20) not null,
  BIRTHDAY date null,
  AUTH_USERNAME varchar(20) not null,
  AUTH_PASSWORD varchar(20) not null,
  AUTH_MAIL varchar(50) not null,
  AUTH_PHONE_NUMBER varchar(20),
  ADR_STREET  varchar(50) not null,
  ADR_ZIPCODE varchar(10) not null,
  ADR_CITY varchar(20) not null,
  ADR_COUNTRY varchar(20) null,
  PRIMARY KEY (ID)
);
